### ISSUE TITLE
how to train/infer with encoder-only experiment?

### ISSUE THREAD

**Issue by qianyizhang** [Edward-Sun/TSP-Detection#1]
if I understand correctly, without Decoder, you would endup with thousands of proposals from FPN, how to train such MultiHeadAttention?

Also, correct me if I am wrong. Your work is pretty much a reformulation of RelationNet, which using attention to reduce FP after standard detection pipeline. Therefore convergence is no longer a issue, but still relies on NMS and anchor/point.

**Comment by xiaomingwang80** [comment]
Hi, I also want to know whether you may share code of encoder-only DERT? @Edward-Sun

**Comment by Edward-Sun** [comment]
Hi @qianyizhang,

For FPN in TSP-RCNN, we use the RPN's output (RoI) to select top proposals. For FPN in TSP-FCOS, we have a Feature of Interest (FoI) score.

As for RelationNet, to my understanding, it is not trained on the end-to-end set prediction objective.

Hi @xiaomingwang80 ,

In encoder-only DETR, the prediction heads are similar to the prediction heads in one-stage detectors.

Here's some code we use, where we use the detectron2 implementation of DETR. I hope they can help you:

```
        images = self.preprocess_image(batched_inputs)
        output = self.detr(images, use_no_sigmoid=True)
        mask = output['mask']
        not_mask = ~mask
        y_embed = not_mask.cumsum(1, dtype=torch.float32)
        y_embed = torch.clamp(y_embed, min=0.5)
        x_embed = not_mask.cumsum(2, dtype=torch.float32)
        x_embed = torch.clamp(x_embed, min=0.5)
        eps = 1e-6
        y_embed = ((y_embed - 0.5) / (y_embed[:, -1:, :] + eps)).flatten(1)
        x_embed = ((x_embed - 0.5) / (x_embed[:, :, -1:] + eps)).flatten(1)

        center_x = output["pred_boxes"][:, :, 0].sigmoid() + x_embed
        center_y = output["pred_boxes"][:, :, 1].sigmoid() + y_embed
        height = (output["pred_boxes"][:, :, 2] - 2.0).sigmoid()
        width = (output["pred_boxes"][:, :, 3] - 2.0).sigmoid()
        # 2.0 as magic number
        output["pred_boxes"] = torch.stack([center_x, center_y, height, width], dim=-1)
```
