### ISSUE TITLE
trained models

### ISSUE THREAD

**Issue by chi0612** [Edward-Sun/TSP-Detection#2]
Can you provide a model of the coco dataset

**Comment by STRUGGLE1999** [comment]
How to train the model? And can you provide the pritrained models?

**Comment by Edward-Sun** [comment]
Hi,

Our script should be able to fully reproduce the trained model.

[TSP-Detection#rreproducing-results](https://github.com/Edward-Sun/TSP-Detection#rreproducing-results)
