### ISSUE TITLE
Run the error in the trin_net_rcnn.py

### ISSUE THREAD

**Issue by 7linlin** [Edward-Sun/TSP-Detection#3]
Hello, I encountered errors in the picture during the process of running the program. Excuse me, is Troi in the picture a module in Python? But after installing the error in the picture, I hope you can help to point out.
![image](https://user-images.githubusercontent.com/97386151/202841264-1d64c345-d507-43fa-9bc1-8211e763dc5d.png)

**Comment by Edward-Sun** [comment]
Hi 7linlin,

Thanks for reporting the bug. The line of code should be

`from rcnn import add_rcnn_config, DetrDatasetMapper`

`from rcnn.my_fast_rcnn_output import fast_rcnn_inference_single_image`

We have fixed it.

Thanks!

**Comment by 7linlin** [comment]
thank you for your reply
